/**
* @description   Case domain object class
* @testClass     NA
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                22/07/2021          Created Product Repository
* ------------------------------------------------------------------------------------ 
*/
public class DO_Product implements IDO_Product{
    public final static String PRODUCT_FAMILY_FUEL = 'Fuel';
}