/**
* @description   ProcessInstanceWorkitem domain object class
* @testClass     N/A
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues                01/09/2021          Created ProcessInstanceWorkitem domain
* ------------------------------------------------------------------------------------ 
*/
public class Do_ProcessInstanceWorkitem implements IDO_ProcessInstanceWorkitem{

    public final static String ACTION_REJECT = 'Reject' ;
    public final static String ACTION_REMOVE = 'Removed';
    public final static String ACTION_APPROVE ='Approve';
}