/**
* @description   UserRole domain object class
* @testClass     N/A
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues                30/08/2021          Created UserRole domain
* ------------------------------------------------------------------------------------ 
*/
public class DO_UserRole implements IDO_UserRole{

    public final static String AT_SALES_MANAGER_ROLE_NAME='ATSalesManager';
}