/**
* @description   User domain object class
* @testClass     N/A
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues                30/08/2021          Created User domain
* ------------------------------------------------------------------------------------ 
*/
public class DO_User implements IDO_Quote{
    
    
}