/**
* @description   Interface for Account domain object class
* @testClass     N/A
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues                25/08/2021          Created Interface for Account domain
* ------------------------------------------------------------------------------------ 
*/
public interface IDO_Account {
   
}