/**
* @description   Interface for UserRole domain object class
* @testClass     N/A
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues               30/08/2021            Created UserRole Domain Interface
* ------------------------------------------------------------------------------------ 
*/
public interface IDO_UserRole {

}