/**
* @description   interface for Contact domain object class
* @testClass     N/A
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                25/08/2021          Created interface for Contact domain
* ------------------------------------------------------------------------------------ 
*/
public interface IDO_Contact {
    Contact createContact(Id id);
}