/**
* @description   interface for Lead domain object class
* @testClass     N/A
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                25/08/2021          Created interface for Lead domain
* ------------------------------------------------------------------------------------ 
*/
public interface IDO_Lead {
}