/**
* @description   Interface for User domain object class
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues               30/08/2021            Created User Domain Interface
* ------------------------------------------------------------------------------------ 
*/
public interface IDO_User {

}