/**
* @description   Interface for ProcessInstanceWorkitem domain object class
* @testClass     N/A
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues               01/09/2021            Created ProcessInstanceWorkitem Domain Interface
* ------------------------------------------------------------------------------------ 
*/
public interface IDO_ProcessInstanceWorkitem {
    
}