/**
* @description   Interface for the Organization Repository
* @testClass     N/A
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* António Santos                  09/08/2021          Interface for the Organization Repository
* ------------------------------------------------------------------------------------ 
*/
public interface IREP_Organization extends FW_ISObjectRep {
    Organization getOrganization();
}