/**
* @description   Interface for the Product Repository
* @testClass     N/A
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                20/07/2021          Interface for the Product Repository
* ------------------------------------------------------------------------------------ 
*/
public interface IREP_Product extends FW_ISObjectRep{
}