/**
* @description   Interface for the CEPSkipValidationRules Repository
* @testClass     N/A
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                24/06/2021          Interface for the CEPSkipValidationRules Repository
* ------------------------------------------------------------------------------------ 
*/
public interface IREP_CEPSkipValidationRules extends FW_ISObjectRep{
}