/**
* @description   Invoice interface
* @testClass     
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Carolina Resende                28/11/2021          Created Invoice interface
* ------------------------------------------------------------------------------------ 
*/
public  interface IREP_Invoice extends FW_ISObjectRep{
    
}