/**
* @description   Interface for the TriggerHandlerSettings Repository
* @testClass     
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                16/11/2021          Created TriggerHandlerSettings Repository
* ------------------------------------------------------------------------------------ 
*/
public interface IREP_TriggerHandlerSettings extends FW_ISObjectRep{

}