/**
* @description   Interface for the ApprovalProcess Service
* @testClass     N/A
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues                30/08/2021           Interface for the ApprovalProcess Service
* ------------------------------------------------------------------------------------ 
*/
public interface ISL_ApprovalProcess {
    void initApprovalProcess( String comments,String RoleName,Id sObjectId );
}