/**
* @description   Intervace class to define when was the last time related activity happened in the contact
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                09/11/2021          Created class
* ------------------------------------------------------------------------------------ 
*/
public interface ISL_ContactRelatedActivity {
    void setContactRelatedActivity(Set<Id> contactIdSet);
}