/**
* @description   TriggerHandlerSettings Repository
* @testClass     
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                16/11/2021          Created TriggerHandlerSettings Repository
* ------------------------------------------------------------------------------------ 
*/
public class REP_TriggerHandlerSettings extends FW_SobjectRep implements IREP_TriggerHandlerSettings{

}