/**
* @description   Interface for the CEPSkipValidationRules Repository
* @testClass     
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                24/06/2021          Created CEPSkipValidationRules Repository
* ------------------------------------------------------------------------------------ 
*/
public class REP_CEPSkipValidationRules extends FW_SobjectRep implements IREP_CEPSkipValidationRules{
    
}