/**
* @description   Product Repository
* @testClass     REP_ProductTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                20/07/2021          Created Product Repository
* ------------------------------------------------------------------------------------ 
*/
public class REP_Product extends FW_SobjectRep implements IREP_Product{
}